<script>
   $(document).ready(function(){
     $("#btnDetail1").click(function(){
       $("table").fadeToggle();
     });
   });
   $(document).ready(function(){
     $("#btnDetail2").click(function(){
       $("ul1").fadeToggle();
     });
   });
</script>